### PR TITLE
testing to see if recorder will replay

### PR DESCRIPTION
**Pull request by CSONG09**

### CODE REVIEW

**Comment by jayfo** [comment]
The current test failure is a glitch in our Travis stuff.  Not an issue with your code.

Want me to merge?

**Comment by CSONG09** [comment]
Hey James, Yes please! Is the test related to the recorder not being able to play on the tablet?? I couldn’t test my change directly on my tablet. Thanks! Clarissa

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by jayfo** [comment]
Closed and re-opened to trigger a re-test now that I've updated to fix the issue with the test framework.

**Comment by jayfo** [comment]
The test framework is just the tests that automatically run on Travis with each pull request.

Nothing to do with your interactive test.

**Pull request merged**
